export type MonthlyMetricKey = 'revenue' | 'expense' | 'profit' | 'newUsers' | 'questions';
export type MonthlyMetricUnit = 'currency' | 'count';
export type MonthlySeries = { year: 2025 | 2026; values: Array<number | null> };
export type MonthlyMetric = { key: MonthlyMetricKey; label: string; unit: MonthlyMetricUnit; series: MonthlySeries[] };
export type MonthlyAchievement = { id: string; text: string };
export type MonthlyTopic = { id: string; title: string; description: string; impact: string };
export type MonthlyToBItem = { id: string; customerName: string; beginningStatus: string; monthlyProgress: string; usageStatus: string; issue: string; nextMonthAction: string };
export type MonthlyInquiryCase = { id: string; title: string; summary: string; response: string; improvement: string };
export type MonthlyBusinessUpdate = { id: string; category: 'product' | 'operations' | 'team'; update: string; purpose: string; currentStatus: string; nextAction: string };
export type MonthlyIssue = { id: string; issue: string; cause: string; impact: string; improvement: string; owner: string; dueDate: string; status: '未着手' | '対応中' | '確認中' | '完了' | '継続観察' };
export type MonthlyPriority = { id: string; initiative: string; purpose: string; successMetric: string; owner: string; dueDate: string; priority: 'High' | 'Medium' | 'Low' };
export type MonthlyReport = { id: string; type: 'monthly'; title: string; reportYear: number; reportMonth: number; status: 'draft' | 'completed'; createdAt: string; updatedAt: string; metrics: MonthlyMetric[]; summary: { overview: string; achievementsToB: MonthlyAchievement[]; achievementsToC: MonthlyAchievement[]; achievementsOperations: MonthlyAchievement[]; importantTopics: MonthlyTopic[]; keyDrivers: string }; tob: MonthlyToBItem[]; toc: { studentInquiries2025: number | null; studentInquiries2026: number | null; teacherInquiries2025: number | null; teacherInquiries2026: number | null; studentTrend: string; teacherTrend: string; cases: MonthlyInquiryCase[] }; businessUpdates: MonthlyBusinessUpdate[]; issues: MonthlyIssue[]; nextMonthPriorities: MonthlyPriority[] };
export const MONTHLY_STORAGE_KEY = 'rakumon-monthly-reports';
export const months = Array.from({ length: 12 }, (_, i) => `${i + 1}月`);
const uid = () => (typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`);
const m = (key: MonthlyMetricKey, label: string, unit: MonthlyMetricUnit, y25: number[], y26: Array<number | null>): MonthlyMetric => ({ key, label, unit, series: [{ year: 2025, values: y25 }, { year: 2026, values: y26 }] });
export const defaultMonthlyMetrics = (): MonthlyMetric[] => [
  m('revenue','月次売上','currency',[980000,1040000,1120000,1180000,1210000,1250000,1290000,1320000,1280000,1360000,1410000,1480000],[1120000,1160000,1210000,1290000,1340000,1410000,1480000,null,null,null,null,null]),
  m('expense','月次費用','currency',[520000,535000,548000,560000,585000,590000,610000,620000,615000,640000,655000,670000],[560000,572000,588000,605000,618000,632000,650000,null,null,null,null,null]),
  m('profit','月次利益','currency',[460000,505000,572000,620000,625000,660000,680000,700000,665000,720000,755000,810000],[560000,588000,622000,685000,722000,778000,830000,null,null,null,null,null]),
  m('newUsers','月次新規登録ユーザー','count',[320,344,361,380,402,420,438,451,430,466,482,510],[382,399,420,446,470,498,526,null,null,null,null,null]),
  m('questions','月次質問数','count',[1280,1340,1420,1510,1588,1660,1725,1810,1760,1885,1960,2050],[1450,1522,1608,1715,1820,1935,2042,null,null,null,null,null]),
];
export function createMonthlyReport(): MonthlyReport { const now = new Date(); return { id: uid(), type:'monthly', title:'Rakumon 月次運営報告', reportYear:2026, reportMonth:7, status:'draft', createdAt:now.toISOString(), updatedAt:now.toISOString(), metrics:defaultMonthlyMetrics(), summary:{ overview:'2026年7月は、法人利用の定着とToC問い合わせ改善が並行して進んだ月でした。売上・利益は前年同月を上回り、質問数も夏期に向けて増加しています。', achievementsToB:[{id:uid(),text:'導入準備中の法人向けに運用説明会を実施し、初回利用までの手順を整理。'}], achievementsToC:[{id:uid(),text:'生徒向けFAQを見直し、解説確認に関する問い合わせ導線を改善。'}], achievementsOperations:[{id:uid(),text:'問い合わせ分類タグを月次集計しやすい粒度に整理。'}], importantTopics:[{id:uid(),title:'夏期利用増への準備',description:'質問数増加を見込み、回答体制とエスカレーション基準を確認。',impact:'繁忙期の品質安定に向けた先行対応。'}], keyDrivers:'法人トライアルの利用開始、新規登録の増加、夏期前の質問需要が主な増加要因です。費用は回答体制強化に伴い増加しています。' }, tob:[{id:uid(),customerName:'架空アカデミー',beginningStatus:'導入準備',monthlyProgress:'運用説明会と利用フロー確認を完了',usageStatus:'一部クラスで試験利用',issue:'先生向け周知資料の補足が必要',nextMonthAction:'初回質問率を確認しフォロー面談'}], toc:{ studentInquiries2025:86, studentInquiries2026:102, teacherInquiries2025:34, teacherInquiries2026:39, studentTrend:'解説内容の確認と学習計画に関する相談が増加。', teacherTrend:'回答方針と稼働調整に関する確認が中心。', cases:[{id:uid(),title:'解説粒度に関する相談',summary:'匿名の生徒から途中式の追加説明を求める問い合わせ。',response:'回答例テンプレートを案内し、先生側にも補足観点を共有。',improvement:'類似質問向けのFAQを追加。'}]}, businessUpdates:[{id:uid(),category:'product',update:'管理画面の検索条件改善を検討',purpose:'問い合わせ確認の時間短縮',currentStatus:'要件整理中',nextAction:'優先度と実装範囲を確認'},{id:uid(),category:'operations',update:'問い合わせタグの整理',purpose:'月次傾向を追いやすくするため',currentStatus:'運用開始',nextAction:'8月データで分類精度を確認'},{id:uid(),category:'team',update:'夏期シフト案の作成',purpose:'質問増加への備え',currentStatus:'候補者確認中',nextAction:'確定シフトを共有'}], issues:[{id:uid(),issue:'一部問い合わせの初動遅れ',cause:'分類判断に時間がかかった',impact:'回答開始までのリードタイムが長くなった',improvement:'一次判断ルールを簡略化',owner:'運営',dueDate:'2026-08-10',status:'対応中'}], nextMonthPriorities:[{id:uid(),initiative:'未利用法人ユーザーへのフォロー',purpose:'導入初月の利用定着',successMetric:'初回質問率30%',owner:'Biz/CS',dueDate:'2026-08-31',priority:'High'}] } }
export const normalizeMonthlyReport = (raw: Partial<MonthlyReport>): MonthlyReport => ({ ...createMonthlyReport(), ...raw, type:'monthly', status: raw.status === 'completed' ? 'completed' : 'draft', metrics: Array.isArray(raw.metrics) ? raw.metrics : defaultMonthlyMetrics() });
export function loadMonthlyReports(): MonthlyReport[] { if (typeof window === 'undefined') return []; const raw = localStorage.getItem(MONTHLY_STORAGE_KEY); if (!raw) { const sample = createMonthlyReport(); localStorage.setItem(MONTHLY_STORAGE_KEY, JSON.stringify([sample])); return [sample]; } try { return (JSON.parse(raw) as Partial<MonthlyReport>[]).map(normalizeMonthlyReport); } catch { return [createMonthlyReport()]; } }
export function saveMonthlyReports(reports: MonthlyReport[]) { localStorage.setItem(MONTHLY_STORAGE_KEY, JSON.stringify(reports.map(normalizeMonthlyReport))); }
export const formatMonthlyValue = (value: number | null | undefined, unit: MonthlyMetricUnit) => value == null ? '—' : unit === 'currency' ? `¥${value.toLocaleString('ja-JP')}` : value.toLocaleString('ja-JP');
export function getMonthlyComparison(metric: MonthlyMetric, month: number) { const i = month - 1; const v2025 = metric.series.find(s=>s.year===2025)?.values[i] ?? null; const v2026 = metric.series.find(s=>s.year===2026)?.values[i] ?? null; const diff = v2025 == null || v2026 == null ? null : v2026 - v2025; const pct = diff == null || !v2025 ? null : (diff / v2025) * 100; return { v2025, v2026, diff, pct }; }
export const addId = <T extends object>(item:T) => ({ id: uid(), ...item });
